name: Forgejo Release Upload

description: Create or reuse a Forgejo release and upload an asset

inputs:
  forgejo_url:
    description: Base URL of Forgejo (e.g. https://git.example.com)
    required: true
  token:
    description: Forgejo API token
    required: true
  tag:
    description: Release tag to use (if not set, tag_file will be used)
    required: false
  tag_file:
    description: File to read tag from (trimmed)
    required: false
    default: version.txt
  release_name:
    description: Release name (defaults to tag)
    required: false
  body:
    description: Release body text
    required: false
    default: ""
  asset_path:
    description: Path to file to upload as release asset
    required: true
  asset_name:
    description: Asset filename shown in release
    required: false

runs:
  using: composite
  steps:
    - name: Create/update release and upload asset
      shell: bash
      env:
        FORGEJO_URL: ${{ inputs.forgejo_url }}
        FORGEJO_TOKEN: ${{ inputs.token }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_TAG_FILE: ${{ inputs.tag_file }}
        INPUT_RELEASE_NAME: ${{ inputs.release_name }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_ASSET_PATH: ${{ inputs.asset_path }}
        INPUT_ASSET_NAME: ${{ inputs.asset_name }}
      run: node "${{ github.action_path }}/release.mjs"
